package com.example.model

/**
 * Models for the Online tab: YouTube content streamed through public,
 * free-software front-end instances (Invidious and Piped). Nothing here
 * talks to YouTube directly — every request goes to an instance from the
 * user's instance list (see [com.example.logic.OnlineVideoRepository]).
 */

/** The two API families the app knows how to talk to. */
enum class OnlineInstanceKind {
    /** Invidious: `/api/v1/...` (videos, captions, channels, search). */
    INVIDIOUS,

    /** Piped API server: `/streams/:id`, `/channel/:id`, `/search`, ... */
    PIPED;

    val label: String
        get() = when (this) {
            INVIDIOUS -> "Invidious"
            PIPED -> "Piped"
        }
}

/**
 * One instance in the user's list. [baseUrl] is normalised (https, no
 * trailing slash) by [com.example.logic.OnlineInstanceStore]. For Piped the
 * URL must be the API host (e.g. `https://pipedapi.kavin.rocks`), not the
 * web front-end.
 */
data class OnlineInstance(
    val baseUrl: String,
    val kind: OnlineInstanceKind,
    val enabled: Boolean = true
) {
    /** Short host name shown in pickers. */
    val host: String get() = baseUrl.removePrefix("https://").removePrefix("http://")
}

/** A YouTube channel the user follows. */
data class OnlineChannel(
    val id: String,
    val name: String,
    val avatarUrl: String? = null,
    val description: String? = null,
    /** True for the built-in list of English-teaching channels. */
    val isDefault: Boolean = false
)

/** One video in a list (channel feed, search result, related videos). */
data class OnlineVideo(
    val id: String,
    val title: String,
    val author: String = "",
    val authorId: String? = null,
    val thumbnailUrl: String? = null,
    val lengthSeconds: Long = 0L,
    val viewCount: Long? = null,
    val publishedText: String? = null,
    /** Upload time as epoch seconds when the instance reports it (0 = unknown); used to merge feeds. */
    val publishedAt: Long = 0L,
    val isLive: Boolean = false
) {
    val watchUrl: String get() = "https://www.youtube.com/watch?v=$id"
}

/** A page of videos plus the token needed to load the next page (null = no more). */
data class OnlineVideoPage(
    val videos: List<OnlineVideo>,
    val continuation: String? = null
)

/** One caption track offered for a video. [url] is absolute. */
data class OnlineCaptionTrack(
    val label: String,
    val languageCode: String,
    val url: String,
    val autoGenerated: Boolean = false,
    /** "text/vtt", "application/ttml+xml" or null when unknown (Piped tells us, Invidious is always VTT). */
    val mimeType: String? = null
) {
    val isEnglish: Boolean get() = languageCode.lowercase().let { it == "en" || it.startsWith("en-") || it.startsWith("en_") }
}

/**
 * One playable rendition. [audioUrl] is present for adaptive video-only +
 * audio pairs. Keeping the pair lets the player use the higher-quality
 * formats instead of discarding them.
 */
data class OnlineStream(
    val url: String,
    val qualityLabel: String,
    val mimeType: String,
    val audioUrl: String? = null,
    /** Numeric height when known (used to sort/pick a default quality). */
    val height: Int = 0,
    /** True when [url] already contains both audio and video. */
    val isProgressive: Boolean = audioUrl == null
)

/** Everything the player needs for one video, resolved through one instance. */
data class OnlineVideoDetails(
    val video: OnlineVideo,
    val description: String = "",
    /**
     * Playable renditions, highest first: muxed progressive files
     * ([OnlineStream.isProgressive]) and paired adaptive video+audio
     * renditions. The player's default pick and fallback order come from
     * [com.example.logic.OnlineStreamSelector], which puts muxed files first.
     */
    val progressiveStreams: List<OnlineStream> = emptyList(),
    /** HLS manifest URL (livestreams and many videos on Piped), if any. */
    val hlsUrl: String? = null,
    /** DASH manifest URL, if any (needs separate audio+video — kept as last resort). */
    val dashUrl: String? = null,
    val captions: List<OnlineCaptionTrack> = emptyList(),
    val related: List<OnlineVideo> = emptyList(),
    /** Which instance answered — the same one is used to fetch its captions. */
    val instance: OnlineInstance
) {
    /** The URL the player should open: a muxed file first, else any rendition, else HLS, else DASH. */
    val playbackUrl: String?
        get() = progressiveStreams.firstOrNull { it.isProgressive }?.url
            ?: progressiveStreams.firstOrNull()?.url
            ?: hlsUrl
            ?: dashUrl
    val playbackIsHls: Boolean get() = progressiveStreams.isEmpty() && hlsUrl != null
}

/**
 * One concrete thing to hand to the player. [audioUrl] is set when video
 * and audio live in two separate files; the player then merges the two
 * sources onto one timeline instead of opening a silent video-only file.
 */
data class OnlinePlaybackSource(
    val url: String,
    val audioUrl: String? = null,
    val mimeType: String? = null,
    /** Index into [OnlineVideoDetails.progressiveStreams], or -1 for a manifest. */
    val streamIndex: Int = -1
)
