package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// ── Light Theme — warm, paper-like tones instead of stark white, to reduce glare during daytime reading ──
val LightPrimary = Color(0xFF3D6E63)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD7EAE3)
val LightOnPrimaryContainer = Color(0xFF16352C)
val LightSecondary = Color(0xFF6B5D4F)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFEDE1D3)
val LightOnSecondaryContainer = Color(0xFF241A0E)
val LightTertiary = Color(0xFF8A5A44)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFBDDC9)
val LightOnTertiaryContainer = Color(0xFF341300)
val LightBackground = Color(0xFFF7F4EF)
val LightOnBackground = Color(0xFF2F2B26)
val LightSurface = Color(0xFFFDFBF7)
val LightOnSurface = Color(0xFF2F2B26)
val LightSurfaceVariant = Color(0xFFECE6DC)
val LightOnSurfaceVariant = Color(0xFF6B6459)
val LightOutline = Color(0xFFA39B8D)
val LightError = Color(0xFFB3261E)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFF9DEDC)
val LightOnErrorContainer = Color(0xFF410E0B)

// ── Dark Theme — soft charcoal instead of pure black, with muted low-glare accents for comfortable night reading ──
val DarkPrimary = Color(0xFF8FCFC0)
val DarkOnPrimary = Color(0xFF00382E)
val DarkPrimaryContainer = Color(0xFF1F4F44)
val DarkOnPrimaryContainer = Color(0xFFABEBDB)
val DarkSecondary = Color(0xFFD6C3AC)
val DarkOnSecondary = Color(0xFF3B2F21)
val DarkSecondaryContainer = Color(0xFF534435)
val DarkOnSecondaryContainer = Color(0xFFF2E1CB)
val DarkTertiary = Color(0xFFE8B597)
val DarkOnTertiary = Color(0xFF4A2A17)
val DarkTertiaryContainer = Color(0xFF64402A)
val DarkOnTertiaryContainer = Color(0xFFFFDBC4)
val DarkBackground = Color(0xFF1B1D1E)
val DarkOnBackground = Color(0xFFE5E1D8)
val DarkSurface = Color(0xFF212426)
val DarkOnSurface = Color(0xFFE5E1D8)
val DarkSurfaceVariant = Color(0xFF34383A)
val DarkOnSurfaceVariant = Color(0xFFC8C2B4)
val DarkOutline = Color(0xFF8D8879)
val DarkError = Color(0xFFF2B8B5)
val DarkOnError = Color(0xFF601410)
val DarkErrorContainer = Color(0xFF8C1D18)
val DarkOnErrorContainer = Color(0xFFF9DEDC)

// ── Shared Accent Colors — desaturated versions of common signal colors so long reading/viewing sessions feel less harsh on the eyes ──
val AccentGreen = Color(0xFF5FA777)
val AccentRed = Color(0xFFD97A6C)
val AccentCyan = Color(0xFF4FB3BF)
val AccentIndigo = Color(0xFF7B87D6)
val AccentAmber = Color(0xFFE0A85A)
