package com.example.logic

import com.example.model.OnlineCaptionTrack
import com.example.model.OnlineInstance
import com.example.model.OnlineInstanceKind
import org.json.JSONArray
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * Caption lookup helpers of the Online tab: the per-instance caption lists
 * that are parsed without a stream lookup, the download order, and the
 * YouTube timedtext fallback URLs.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [35])
class OnlineCaptionSourcesTest {

    private val invidious = OnlineInstance("https://inv.example.org", OnlineInstanceKind.INVIDIOUS)
    private val piped = OnlineInstance("https://pipedapi.example.org", OnlineInstanceKind.PIPED)

    @Test
    fun `invidious caption list is parsed from the captions endpoint`() {
        val arr = JSONArray(
            """[{"label":"English","languageCode":"en","url":"/api/v1/captions/abc?label=English"},
               {"label":"English (auto-generated)","languageCode":"en","url":"/api/v1/captions/abc?label=English+%28auto-generated%29"},
               {"label":"broken","languageCode":"de","url":""}]"""
        )
        val tracks = OnlineVideoRepository.parseInvidiousCaptions(invidious, arr)
        assertEquals(2, tracks.size)
        assertEquals("https://inv.example.org/api/v1/captions/abc?label=English", tracks[0].url)
        assertEquals(false, tracks[0].autoGenerated)
        assertEquals(true, tracks[1].autoGenerated)
        assertTrue(OnlineVideoRepository.parseInvidiousCaptions(invidious, null).isEmpty())
    }

    @Test
    fun `piped subtitles are parsed`() {
        val arr = JSONArray(
            """[{"name":"English","code":"en","url":"https://pipedproxy.example.org/api/timedtext?v=abc","autoGenerated":true,"mimeType":"text/vtt"}]"""
        )
        val tracks = OnlineVideoRepository.parsePipedCaptions(piped, arr)
        assertEquals(1, tracks.size)
        assertEquals("en", tracks[0].languageCode)
        assertEquals(true, tracks[0].autoGenerated)
        assertEquals("text/vtt", tracks[0].mimeType)
    }

    @Test
    fun `english written captions are tried first`() {
        val tracks = listOf(
            OnlineCaptionTrack("Deutsch (auto)", "de", "u1", autoGenerated = true),
            OnlineCaptionTrack("English (auto)", "en", "u2", autoGenerated = true),
            OnlineCaptionTrack("Français", "fr", "u3"),
            OnlineCaptionTrack("English", "en-US", "u4")
        )
        assertEquals(listOf("u4", "u2", "u3", "u1"), OnlineVideoRepository.orderCaptionTracks(tracks).map { it.url })
    }

    @Test
    fun `timedtext fallback asks for manual then auto english vtt`() {
        val tracks = OnlineVideoRepository.timedTextTracks("dQw4w9WgXcQ")
        assertEquals(2, tracks.size)
        assertEquals("https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&fmt=vtt&lang=en", tracks[0].url)
        assertEquals("https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&fmt=vtt&lang=en&kind=asr", tracks[1].url)
        assertTrue(tracks[1].autoGenerated)
        // Anything that is not a YouTube id never reaches the network.
        assertTrue(OnlineVideoRepository.timedTextTracks("../../etc").isEmpty())
    }
}
